### ISSUE TITLE
[Request] Is it possible to show the actual kubeconfig used near to, for example, the branch of git?

### ISSUE THREAD

**Issue by jotedia** [ebarped/kubeswap#2]
![image](https://github.com/ebarped/kubeswap/assets/28892625/ab779655-ad72-462f-a03f-3ce0ff19bf9e)

I want to ask if it's possible to show the kubeconfig used near to the actual path.

Thanks in advance @ebarped.

**Comment by ebarped** [comment]
That is a shell/prompt related configuration. You should check for projects like [kube-ps1](https://github.com/jonmosco/kube-ps1).

You are welcome!
